### PR TITLE
Added Like button

### PR DESCRIPTION
**Pull request by karthickkumarsm**
Added a like button which is functional

### CODE REVIEW

**Comment by karthickkumarsm** [comment]
Like button functionality code is available at dashboard.dart file

**Comment by Yashshukla11** [comment]
resolve the conflicts

**Review by Yashshukla11 — APPROVED** [review]

**Comment by karthickkumarsm** [comment]
please add gssoc label to this pull request

**Comment by karthickkumarsm** [comment]
@Yashshukla11

**Comment by karthickkumarsm** [comment]
@Yashshukla11 Brother please assign gssoc label and level label.

**Pull request merged**
