### PR TITLE
CodeQL added

### PR DESCRIPTION
**Pull request by prajapatihet**
Issue #119 done

### CODE REVIEW

**Review by Yashshukla11 — APPROVED** [review]

**Comment by prajapatihet** [comment]
Hey @Yashshukla11 can you add label here

**Comment by prajapatihet** [comment]
hey @Yashshukla11 please add proper labels here!!!!!

**Comment by prajapatihet** [comment]
hey @Yashshukla11 please add proper labels here!!!!!
you merged the PR but didn't mentioned labels here

**Comment by prajapatihet** [comment]
hey @Yashshukla11 please add proper labels here!!!!!
you merged the PR but didn't mentioned labels here
I am GSSoC Contributor

**Comment by prajapatihet** [comment]
@Yashshukla11 Could you please assign the appropriate labels?

**Pull request merged**
